name: flameo
description: Galería online para artistas emergentes. Cualquier artista puede subir sus obras y venderlas de forma gratuita
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  sidebarx: ^0.14.0
  firebase_core: ^2.17.0
  material_segmented_control: 4.0.0
  provider: ^6.0.4
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.3.59
  fl_chart: ^0.55.2
  quiver: ^3.1.0
  qr_flutter: ^4.0.0
  liquid_swipe: ^3.0.0
  visibility_aware_state: ^1.0.5
  dart_ipify: ^1.1.1
  geolocator: ^9.0.2
  carousel_slider: ^4.2.1
  diacritic: ^0.1.3
  string_similarity: ^2.0.0
  firebase_storage: ^11.2.8
  file_picker: ^5.2.5
  image_network: ^2.5.1
  http: ^0.13.5
  logging: ^1.1.1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.10
  image_picker_for_web: ^2.1.12
  animations: ^2.0.7
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  image: ^3.0.2
  collection: ^1.17.1
  google_fonts: ^4.0.4
  badges: ^3.1.1
  email_validator: ^2.1.17
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+3
  reorderables: ^0.6.0
  get: ^4.6.6
  checkbox_formfield: ^0.2.0
  timeline_tile: ^2.0.0
  flutter_lints: ^2.0.3
  meta_seo: ^3.0.5
  searchfield: ^0.8.4
  connectivity_plus: ^2.1.0
  stack_trace: ^1.11.0
  flutter_markdown: ^0.6.18
  font_awesome_flutter: ^10.5.0
  like_button: ^2.0.5
  gap: ^3.0.1
  seo_renderer: ^0.6.0
  seo: ^0.0.5
  qrcode_reader_web: ^1.1.1
flutter_native_splash:
  color: '#ffffff'
  image: imgs/logo.png
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - imgs/products/
    - imgs/
    - imgs/marketing/
    - imgs/carrousel_art_computer/
    - imgs/carrousel_art_phone/
    - config/
    - seo/
    - docs/
  fonts:
    - family: titleFont
      fonts:
        - asset: fonts/Fontanero-Bevel-FFP.ttf
        - asset: fonts/Fontanero-FFP.ttf
    - family: subtitleFont
      fonts:
        - asset: fonts/junegull.ttf