name: Deploy to Firebase Hosting stg on PR to main
on:
  pull_request:
    branches:
      - main
    paths:
      - assets/**
      - seo/**
      - config/**
      - fonts/**
      - imgs/**
      - lib/**
      - .firebaserc
      - .metadata
      - cors.json
      - firebase.json
      - firestore.indexes.json
      - firestore.rules
      - pubspec.lock
      - pubspec.yaml
      - storage.rules
      - .github/workflows/firebase-hosting-pull-request.yml
permissions: write-all

jobs:
  build_and_deploy_web:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: flutter --version

      - name: Generate firebase_options.dart
        run: |
          sed -e "s/%%FIREBASE_API_KEY%%/${{ secrets.FIREBASE_API_KEY }}/" \
          -e "s/%%FIREBASE_APP_ID%%/${{ secrets.FIREBASE_APP_ID }}/" \
          -e "s/%%FIREBASE_MESS_SENDER_ID%%/${{ secrets.FIREBASE_MESS_SENDER_ID }}/" \
          -e "s/%%FIREBASE_PROJECT_ID%%/${{ secrets.FIREBASE_PROJECT_ID }}/" \
          -e "s/%%FIREBASE_AUTH_DOMAIN%%/${{ secrets.FIREBASE_AUTH_DOMAIN }}/" \
          -e "s/%%FIREBASE_STORAGE_BUCKET%%/${{ secrets.FIREBASE_STORAGE_BUCKET }}/" \
          -e "s/%%FIREBASE_MEASUREMENT_ID%%/${{ secrets.FIREBASE_MEASUREMENT_ID }}/" \
          firebase_options.dart.template > lib/firebase_options.dart

      - name: Analyze project
        run: flutter analyze

      - name: Prepare test configuration
        run: cp config/test.json config/__config__.json

      - name: Build web
        run: flutter build web --release -t lib/main.dart

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLAMEOAPP_PYME }}'
          channelId: live
          target: stg
          projectId: flameoapp-pyme
