name: Deploy to Firebase Hosting on push to main
on:
  push:
    branches:
      - main
    paths:
      - assets/**
      - seo/**
      - config/**
      - fonts/**
      - imgs/**
      - lib/**
      - .firebaserc
      - .metadata
      - cors.json
      - firebase.json
      - firestore.indexes.json
      - firestore.rules
      - pubspec.lock
      - pubspec.yaml
      - storage.rules

jobs:
  build_and_deploy_web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install and configure flutter
        run: |
          sudo snap install flutter --classic
          flutter config --enable-web
        
      - name: Analyze project
        run: flutter analyze

      - name: Prepare pro configuration
        run: cp config/pro.json config/__config__.json

      - name: Build web
        run: flutter build web --release -t lib/main.dart

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLAMEOAPP_PYME }}'
          channelId: live
          target: prod
          projectId: flameoapp-pyme

      - name: Prepare art configuration
        run: cp config/art.json config/__config__.json

      - name: Build flameoart web
        run: flutter build web --release -t lib/main.dart

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLAMEOAPP_PYME }}'
          channelId: live
          target: art
          projectId: flameoapp-pyme
